# ORCA conda environment
# Tahmid Anwar's Part

name: ORCA

channels:
  - conda-forge
  - defaults
  - bioconda          
  - conda-forge     

dependencies:
  - python=3.10
  - biopython=1.83        
  - regex=2023.12.25             
  - matplotlib=3.8.3   

  
